CREATE TABLE topicos(
	
	id BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	titulo VARCHAR(255) NOT NULL UNIQUE,
	mensagem MEDIUMTEXT NOT NULL UNIQUE,
	data_de_criacao DATETIME NOT NULL,
	status_topico VARCHAR(100) NOT NULL,
	autor VARCHAR(255) NOT NULL,
	curso VARCHAR(255) NOT NULL,
	ativo BOOLEAN NOT NULL,
	
	PRIMARY KEY(id)
	
	
);